build:
  image: default-bionic
  environment:
    php:
      version: 8.3.3
      ini:
        xdebug.mode: coverage
  nodes:
    analysis:
      project_setup:
        override:
          - true
      tests:
        override:
          - php-scrutinizer-run
          - command: phpcs-run
            use_website_config: true
checks:
  php:
    code_rating: true
    duplication: true
    excluded_dependencies:
      - phpunit/phpunit
tools:
  php_cs_fixer:
    config: .phpcs
